# Start with the official Node image as a base
FROM node:14

# Set the working directory
WORKDIR /

# Copy package.json and package-lock.json (if available)
COPY package.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the backend application
COPY . .

# Expose the port the app runs on
EXPOSE 8888

# Start the app
CMD ["npm","dev"]
